version: "3.8"
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    ports:
      - 5000
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444